project:
  type: website
  output-dir: docs
  resources:
    - assets

website:
  title: "GeoLink"
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Sources
        menu:
          - href: articles/geodata_sources.qmd
            text: Overview
          - href: articles/data_geospatialdata.qmd
            text: GeoSpatialData on R Drive
          - href: articles/data_grass.qmd
            text: GRASS GIS
          - href: articles/data_gisdb.qmd
            text: PostgreSQL GIS Database
          
      - text: Functions
        menu:
          - href: articles/functions.qmd
            text: Overview
          - href: articles/functions_geospatialdata.qmd
            text: R:GeoSpatialData

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - _favicon.html


