project:
  type: website
  output-dir: docs

website:
  title: "GeoLink"
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Sources
        menu:
          - href: articles/geodata_sources.qmd
            text: Overview
          - href: articles/data_geospatialdata.qmd
            text: GeoSpatialData on R Drive
          - href: articles/data_grass.qmd
            text: GRASS GIS
          - href: articles/data_gisdb.qmd
            text: PostgreSQL GIS Database

format:
  html:
    theme: cosmo
    toc: true
    include-in-header: |
      <link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon-16x16.png">
      <link rel="manifest" href="assets/site.webmanifest">

